import {auth,db}from './firebase-config.js';
import{onAuthStateChanged,signOut}from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-auth.js';
import{doc,getDoc,collection,query,where,getDocs,addDoc,serverTimestamp,updateDoc}from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js';
const $=id=>document.getElementById(id);let user;
const estados={aguardando_pagamento:'Aguardando pagamento',recebido:'Recebida',em_preparacao:'Em preparação',enviado:'Enviada',concluido:'Concluída',cancelado:'Cancelada'};
const money=v=>`${Number(v||0).toLocaleString('pt-AO')} Kz`;
function dataTexto(v){if(!v)return 'Data não disponível';try{return v.toDate().toLocaleString('pt-AO')}catch{return 'Data não disponível'}}
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

onAuthStateChanged(auth,async u=>{if(!u){location.href='login.html';return}user=u;const s=await getDoc(doc(db,'usuarios',u.uid));const v=s.exists()?s.data():{};if(v.tipo!=='vendedor'){alert('Esta área é exclusiva para vendedores.');location.href=v.tipo==='admin'?'admin.html':'index.html';return}$('nome-loja').textContent=v.nomeLoja||'Minha loja';$('email').textContent=u.email||v.email||'';const ativo=v.subscricaoAtiva===true;$('estado').textContent=v.estadoConta==='bloqueado'?'Conta bloqueada':ativo?'Conta ativa':'Conta aguardando subscrição';$('sub-info').textContent=ativo?`Subscrição ${v.planoSubscricao||'ativa'} ativa${v.proximaCobrancaEm?' até à próxima cobrança.':''}`:'A subscrição ainda não está ativa. Solicite a renovação e aguarde a confirmação do administrador.';await carregarProdutos();await carregarPedidos()});
$('btn-logout').onclick=()=>signOut(auth);
$('btn-pedir').onclick=async()=>{if(!user)return;const cfg=await getDoc(doc(db,'configuracao','subscricao'));const c=cfg.exists()?cfg.data():{plano:'mensal',valor:0};try{await addDoc(collection(db,'pedidosSubscricao'),{vendedorId:user.uid,email:user.email||'',adminEmail:'domingosferrazfonseca283@gmail.com',plano:c.plano||'mensal',valor:Number(c.valor||0),estado:'aguardando_pagamento',criadoEm:serverTimestamp()});alert('Pedido enviado ao administrador.');}catch(e){alert('Não foi possível enviar o pedido: '+e.message)}};
$('btn-produto').onclick=async()=>{if(!user)return;const nome=$('produto-nome').value.trim(),preco=Number($('produto-preco').value),stock=Math.floor(Number($('produto-stock').value)),categoria=$('produto-categoria').value.trim(),descricao=$('produto-descricao').value.trim();if(!nome||preco<=0||!Number.isFinite(stock)||stock<0)return alert('Informe nome, preço e stock válidos.');try{await addDoc(collection(db,'produtos'),{vendedorId:user.uid,nome,preco,stock,categoria,descricao,ativo:false,estadoAprovacao:'pendente',criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()});$('produto-nome').value='';$('produto-preco').value='';$('produto-stock').value='';$('produto-categoria').value='';$('produto-descricao').value='';alert('Produto enviado para aprovação do administrador.');await carregarProdutos()}catch(e){alert('Não foi possível publicar: '+e.message)}};
async function carregarProdutos(){const s=await getDocs(query(collection(db,'produtos'),where('vendedorId','==',user.uid)));$('produtos-list').innerHTML=s.empty?'<p>Nenhum produto.</p>':s.docs.map(d=>{const p=d.data();const stock=Math.max(0,Math.floor(Number(p.stock)||0));return `<article><strong>${esc(p.nome||'Produto')}</strong><br>${money(p.preco)} · Stock: ${stock} · ${esc(p.categoria||'outros')} · ${p.ativo===true?'Publicado':'Aguardando aprovação'}</article>`}).join('')}
async function carregarPedidos(){const el=$('pedidos-list');if(!el)return;el.textContent='A carregar encomendas...';try{const s=await getDocs(query(collection(db,'pedidos'),where('sellerIds','array-contains',user.uid)));if(s.empty){el.innerHTML='<p>Nenhuma encomenda encontrada.</p>';return}const pedidos=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>{const ta=a.criadoEm?.toMillis?.()||0,tb=b.criadoEm?.toMillis?.()||0;return tb-ta});el.innerHTML=pedidos.map(p=>{const meusItens=Array.isArray(p.items)?p.items.filter(i=>i?.vendedorId===user.uid):[];const totalVendedor=meusItens.reduce((sum,i)=>sum+(Number(i.preco)||0)*(Number(i.quantidade)||1),0);const itens=meusItens.length?meusItens.map(i=>`${esc(i.nome||'Produto')} × ${Number(i.quantidade)||1}`).join('<br>'):'Produtos desta encomenda';const estado=p.orderStatus||'aguardando_pagamento';return `<article style="padding:14px 0;border-bottom:1px solid #ddd"><strong>Encomenda #${esc(p.id)}</strong><br><small>${dataTexto(p.criadoEm)}</small><p><strong>Cliente:</strong> ${esc(p.customer?.nome||'Não informado')} · ${esc(p.customer?.telefone||'Sem telefone')}<br><strong>Itens:</strong><br>${itens}<br><strong>Total dos meus produtos:</strong> ${money(totalVendedor)}<br><strong>Pagamento:</strong> ${esc(p.paymentMethod||'Não informado')} · ${esc(p.paymentStatus||'pendente')}</p><label for="estado-${esc(p.id)}">Estado da encomenda</label><select id="estado-${esc(p.id)}" data-order-id="${esc(p.id)}">${Object.entries(estados).map(([key,label])=>`<option value="${key}" ${estado===key?'selected':''}>${label}</option>`).join('')}</select></article>`}).join('');el.querySelectorAll('select[data-order-id]').forEach(select=>select.addEventListener('change',async e=>{await alterarEstadoPedido(e.currentTarget.dataset.orderId,e.currentTarget.value)}))}catch(e){el.innerHTML=`<p>Não foi possível carregar as encomendas: ${esc(e.message)}</p>`}}
async function alterarEstadoPedido(id,estado){try{await updateDoc(doc(db,'pedidos',id),{orderStatus:estado});alert('Estado da encomenda atualizado.');await carregarPedidos()}catch(e){alert('Não foi possível atualizar a encomenda: '+e.message)}}